//! Errors generated by this library and wrappers around the underlying C library

#[derive(Debug, thiserror::Error)]
/// Errors generated by supernovas
pub enum Error {
    #[error("The function was passed an invalid string")]
    InvalidString,
    #[error("The underlying C library errored: {0}")]
    LowerLevel(i32),

    #[cfg(feature = "hifitime")]
    #[error("Error from the web requests")]
    Reqwest(#[from] reqwest::Error),

    #[cfg(feature = "calceph")]
    #[error("Error from CALCEPH")]
    Calceph(#[from] calceph::Error),

    #[cfg(feature = "calceph")]
    #[error("CALCEPH provider not loaded")]
    EphemNotLoaded,
}
